# Generated by Django 5.2.7 on 2025-11-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translatedtext',
            name='object_id',
            field=models.BigIntegerField(),
        ),
    ]
