# Generated by Django 5.2.7 on 2025-12-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_userotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userotp',
            name='failed_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='userotp',
            index=models.Index(fields=['user', 'created_at'], name='authApp_use_user_id_6fd405_idx'),
        ),
    ]
